### ISSUE TITLE
Add an appropriate error message for Yelp API exhausation

### ISSUE THREAD

**Issue by marutim** [WordImpress/Yelp-Widget-Premium#29]
## Issue Overview
When the Yelp API is exhausted it throws the error "_The default Yelp API has exhausted its daily limit. Please enable your own API Key in your Yelp Widget Pro settings._"

This is not appropriate with the current version of the plugin, where the option to add "own API key" is removed. 

## Expected Behavior
Add an appropriate error message.

## Related issue link from Helpscout
https://secure.helpscout.net/conversation/434492171/10443/?folderId=672191

## Screenshot
![index php 1701x823](https://user-images.githubusercontent.com/3498917/30642436-96281702-9e28-11e7-96c0-6c9865bda502.png)

**Comment by kevinwhoffman** [comment]
Closing since this is error should no longer occur after the transition from Yelp API v2 to v3 in v1.9.6 of the plugin.

See #31 #33 and #35 for details.
