### ISSUE TITLE
Create new plugin banner to notify users of plugin's end of life

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Yelp-Widget-Premium#37]
## Issue Overview

We need to notify users that this plugin will no longer be supported or developed by end of 2018.

- [x] Notify users of plugin's end of life via a dismissible banner
- [x] Offer users an upgrade path with 1 free year of WPBR
- [x] Remove references to bundle / pro upgrade throughout
- [x] Notify users of the end of life on the settings page and widget
- [x] Remove old license notice

Proposed text:

> On August 1st, 2018, Yelp Widget Premium became part of our brand new WordPress reviews plugin called WP Business Reviews. The Yelp Widget Premium plugin currently installed will be supported until December 31st, 2018. We are offering 1 year for free as a way to show you our appreciation for being a valued customer. 
> 
> Upgrade now to WP Business Reviews 
> Have a Question? Contact Support

**Comment by mathetos** [comment]
I think this should be both a dismissable banner, AND a static notification at the top of the settings area. You made it very succinct, but there's a couple details missing, specifically that the free trial is (currently) only available until Sept 30. This is a little longer, but I think it's worth being a bit more hand-holding and detailed:

> Yelp Widget Premium is Being Sunset
> 
> On August 1st, 2018, we launched a brand new way to embed your business reviews in your WordPress website. We call it "WP Business Reviews". It supports Yelp Reviews as well as Google, Facebook, and more. Therefore, we are sunsetting Yelp Widget Premium. Until December 31, 2018 you will continue to receive Priority Support for Yelp Widget Premium.
> 
> To show you our appreciation as a loyal Yelp Widget Premium customer, we are offering you a free year of WP Business Reviews. Please act now, the free trial offer ends on September 30, 2018.
> 
> Upgrade now to WP Business Reviews
> Have a Question? Contact Support

**Comment by mathetos** [comment]
@DevinWalker the link to use is: `https://wpbusinessreviews.com/freetrial18`

**Comment by DevinWalker** [comment]
## Sunset Notice Comps

Here's what I'm thinking for the sunset notices.

- Upgrade link stays until 12/31/18 
- Support link goes to WPBR contact page with "Upgrade question" pre-selected: https://wpbusinessreviews.com/contact/

### Plugin listing page:

- Dismissible using transient for 48 hours
- Will reappear to nag user to upgrade

![2018-08-23_14-46-14](https://user-images.githubusercontent.com/1571635/44554004-395dc100-a6e4-11e8-9dd3-b584cd0da173.png)

###  Settings Page

- non-dismissible 

![2018-08-23_14-51-17](https://user-images.githubusercontent.com/1571635/44553987-2b0fa500-a6e4-11e8-81d2-b0e6a345508a.png)
